apiVersion: v1
kind: Pod
metadata:
  name: random-app-pod
  labels:
    app: random-app
spec:
  containers:
    - name: random-app
      image: random-app:latest  
      ports:
        - containerPort: 8080  
      env:
        - name: MIN
          value: "1"  # giá trị môi trường MIN
        - name: MAX
          value: "10"  # giá trị môi trường MAX
        - name: PORT
          value: "8080"  # giá trị môi trường PORT
---          
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-app-deployment
  labels:
    app: random-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: random-app
  template:
    metadata:
      labels:
        app: random-app
    spec:
      containers:
        - name: random-app
          image: random-app:latest  
          ports:
            - containerPort: 8080  
          env:
            - name: MIN
              value: "1"  # Giá trị môi trường MIN
            - name: MAX
              value: "10"  # Giá trị môi trường MAX
            - name: PORT
              value: "8080"  # Giá trị môi trường PORT

---
apiVersion: v1
kind: Service
metadata:
  name: random-app-service
spec:
  selector:
    app: random-app
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8080  
  type: clusterIP  